name: Deploy Frontend

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Check S3 bucket
        run: |
          aws s3 ls s3://anguler-project-new

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync \
            dist/fantasy-poc/browser/ \
            s3://anguler-project-new \
            --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3D84TE1CQO49C \
            --paths "/*"

      - name: Deployment completed
        run: |
          echo "======================================"
          echo "Frontend Deployment Completed"
          echo "======================================"
          echo "S3 Bucket        : anguler-project-new"
          echo "AWS Region       : eu-west-2"
          echo "CloudFront ID    : E3D84TE1CQO49C"
          echo "S3 Upload        : SUCCESS"
          echo "CloudFront       : INVALIDATED"
          echo "======================================"
